# This file configures the controllers for the supre robot.
/supre_robot_follower/controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    # Broadcaster for joint states
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    left_arm_controller:
      type: position_controllers/JointGroupPositionController
    right_arm_controller:
      type: position_controllers/JointGroupPositionController
    left_arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    right_arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
# Parameters for the left arm controller
/supre_robot_follower/left_arm_controller:
  ros__parameters:
    joints:
      - follower_left_arm_joint_1
      - follower_left_arm_joint_2
      - follower_left_arm_joint_3
      - follower_left_arm_joint_4
      - follower_left_arm_joint_5
      - follower_left_arm_joint_6
      - follower_left_arm_joint_7
    interface_name: "position"

# Parameters for the right arm controller
/supre_robot_follower/right_arm_controller:
  ros__parameters:
    joints:
      - follower_right_arm_joint_1
      - follower_right_arm_joint_2
      - follower_right_arm_joint_3
      - follower_right_arm_joint_4
      - follower_right_arm_joint_5
      - follower_right_arm_joint_6
      - follower_right_arm_joint_7      
    interface_name: "position"

/supre_robot_follower/left_arm_trajectory_controller:
  ros__parameters:
    joints:
      - follower_left_arm_joint_1
      - follower_left_arm_joint_2
      - follower_left_arm_joint_3
      - follower_left_arm_joint_4
      - follower_left_arm_joint_5
      - follower_left_arm_joint_6
      - follower_left_arm_joint_7 
    command_interfaces: # <--- 硬件是否提供了这些接口？
        - position
    state_interfaces:
        - position
        - velocity

/supre_robot_follower/right_arm_trajectory_controller:
  ros__parameters:
    joints:
      - follower_right_arm_joint_1
      - follower_right_arm_joint_2
      - follower_right_arm_joint_3
      - follower_right_arm_joint_4
      - follower_right_arm_joint_5
      - follower_right_arm_joint_6
      - follower_right_arm_joint_7 
    command_interfaces: # <--- 硬件是否提供了这些接口？
        - position
    state_interfaces:
        - position
        - velocity        