# This file configures the controllers for the supre robot.

/supre_robot_leader/controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    # Broadcaster for joint states
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    left_arm_controller:
      type: position_controllers/JointGroupPositionController
    right_arm_controller:
      type: position_controllers/JointGroupPositionController
    misumi_gripper_controller:
      type: forward_command_controller/ForwardCommandController
# Parameters for the left arm controller
/supre_robot_leader/left_arm_controller:
  ros__parameters:
    joints:
      - left_arm_joint_1
      - left_arm_joint_2
      - left_arm_joint_3
      - left_arm_joint_4
      - left_arm_joint_5
      - left_arm_joint_6
      - left_arm_joint_7
    interface_name: "position"

# Parameters for the right arm controller
/supre_robot_leader/right_arm_controller:
  ros__parameters:
    joints:
      - right_arm_joint_1
      - right_arm_joint_2
      - right_arm_joint_3
      - right_arm_joint_4
      - right_arm_joint_5
      - right_arm_joint_6
      - right_arm_joint_7
    interface_name: "position"

/supre_robot_leader/misumi_gripper_controller:
  ros__parameters:
    joints: 
      - gripper_joint # Must match the joint name in the URDF
    interface_name: position
